### ISSUE TITLE
Property reference resolution implemented?

### ISSUE THREAD

**Issue by tomhalley** [icarus-sullivan/serverless-plugin-modularize#14]
I'm not having any luck with variable resolution on merged serverless configs using this plugin.

I have one lerna monorepo project with two services, both tested and deploying successfully independently, but when merged with modularize, I get cloudwatch errors like the below:

```
1 validation error detected: Value '${self:provider.environment.DYNAMODB_TABLE}' at 'tableName' failed to satisfy constraint:
```

Here's my root serverless.yml file

```
service: my-funky-service

unresolvedVariablesNotificationMode: error
configValidationMode: error

plugins:
  - serverless-plugin-modularize

custom:
  modularize:
    glob: './services/*/serverless.yml'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: "production"
```

I noticed there aren't any variables in your examples to test this with, so am I correct in thinking this is a missing feature?

**Comment by icarus-sullivan** [comment]
@tomhalley Hey, thanks for using the plugin. Can you provide a sample (subset) of the provider defined in one of your services located with the glob pattern? 

Also, last I was aware, variables for the Serverless framework are defined within the `custom` block of yaml. If I'm misunderstanding the issue please let me know.

**Comment by icarus-sullivan** [comment]
In example:

_service/a/serverless.yaml_
```
custom:
  some_variable: true
  
provider:
  environment:
    VARIABLE_FOR_A: 'http://localhost:3000'

```

_service/b/serverless.yaml_
```
custom:
  another_variable: 'a variable defined in b'
```

When merged at the root level, these values will be:

```
custom:
  some_variable: true
  another_variable: 'a variable defined in b'

provider:
  environment:
    VARIABLE_FOR_A: 'http://localhost:3000'
```

**Comment by tomhalley** [comment]
Ah sorry maybe the wrong terminology, being a bit simple today. I mean when you're referencing properties within the same serverless.yml file, like `${self:provider.environment.DYNAMODB_TABLE}`

Here is a subset of one of the sub-services serverless.yml configs with just the DYNAMODB_TABLE property that isn't resolving properly.

```
service: my-funky-service-api

unresolvedVariablesNotificationMode: error
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  region: XXXXX
  environment:
    DYNAMODB_TABLE: ${self:custom.dynamoDbTableName}

custom:
  dynamoDbTableName: ${self:service}-${env:stage, self:provider.stage}-Table

resources:
  Resources:
    FunkyDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.dynamoDbTableName}
```

And judging by the error I'm seeing in AWS, it looks like these variables are going straight through to AWS without being resolved by serverless first. Again, tested these independently and all fine, but have issues when running through the root serverless.yml.

**Comment by tomhalley** [comment]
This is the serverless documentation I'm working from: https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-properties-in-serverlessyml

**Comment by icarus-sullivan** [comment]
How are you deriving env:stage here?
```
custom:
  dynamoDbTableName: ${self:service}-${env:stage, self:provider.stage}-Table
```
If this env:stage isn't provided, it should default to `self:provider.stage`, but from the example's provided I don't see a stage value present in either provider. 

That could be why you aren't able to resolve the values 🤷🏻 .  Unless they changed something shouldn't stage be resolved via options like: `${opts:stage, '<default_value'>}`

**Comment by tomhalley** [comment]
As I said before, the independent services deployed absolutely fine by themselves with `sls deploy`. I've gone back and changed it to try your suggestion and then running `sls deploy --stage=dev` and exactly the same result; both services deploying independently, but same error as before hen deploying through serverless-plugin-modularize:

```
1 validation error detected: Value '${self:custom.dynamoDbTableName}' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+ (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: BDO9O35Q8EIOOFU5JE8QD9DURNVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)
```

**Comment by icarus-sullivan** [comment]
Okay, I think there may have been some misunderstanding about the way this plugin operates. It doesn't merge multiple services together, it allows you to modularize sections of your project/service. For example, lets say apis are separated from some non user-facing lambdas. You would/could define them in an api/ folder with a potential file called apis.yaml which could be merged into the main root service.

**Comment by icarus-sullivan** [comment]
Assuming I'm wrong and your aren't trying to merge services. I have seen a lot of projects using the file suffix `.yaml`. I'm wondering if it could be something as simple as that? 

Also, I generated a small project using your examples and modified the glob pattern to use:

```
custom:
  modularize:
    glob: 'services/*/serverless.yaml'
 ```
 
 
   ... and it worked. 
   
   You can verify if things are merging correctly by running this command in the root of your project. 
   
   ```
   npx serverless modularize merged
   ```
   
   This should spit out the result of the merged yaml/yml files. 
   
   
   Example project tree:
```
├── node_modules
├── package.json
├── serverless.yaml
├── services
│   └── a
│       └── serverless.yaml
└── yarn.lock
```

**Comment by tomhalley** [comment]
Ah okay that's interesting, because what I'm trying to do is have the
flexibility to run my API service as its own service locally, which would
require it to have a service name and stuff like provider runtime, while at
the same time have the ability to pull it into a larger service file and
deploy it in a stack along with a database and frontend app. Your plugin is
the closest thing I've found so far, and to be honest I'm unsure why this
isn't a more common approach.

I assumed what your plugin would be doing would be to ignore any service
names pulled in from child files, merge all of the config sections you have
listed as supported in the readme, and ignore everything else.

Anyway, that's all irrelevant. I forked your repo and tried to recreate the
issue with some changes to your example, and it works fine on serverless 1
but breaks in 2. Is 2 supported with your plugin?

**Comment by bros4president** [comment]
I run into the same issue when upgrading from Serverless 2.11.1 to 2.45.1

Apparently referenced variables that are in the same file will render, but those references that are in other files do not.

Example,  `${self:provider.stage}`, defined in the root serverless.yml file, will not render in any "child" file, unless it's redefined in it.
`${self:custom.x}` will not render if `x` is defined under the root file's `custom` variable, but it will if it's defined under the same file's `custom`.

When the variable is not rendered, the expression will be kept in the string (instead of rendering empty), hence the validation error, as table names cannot contain `$` or `{`.

Thanks :)

**Comment by icarus-sullivan** [comment]
> I assumed what your plugin would be doing would be to ignore any service
names pulled in from child files, merge all of the config sections you have
listed as supported in the readme, and ignore everything else.

Now that's a thought, I just released a 2.0.0 version. I can probably add a delete for any `service` value for incoming configs and see if it does what you want.

**Comment by Eggwise** [comment]
@icarus-sullivan Thanks for developing this plugin.
This is a very nice program but while it's aim is to increase flexiibility and modularity it gives extra restrictions.


I run into the same problem as @bros4president .


I have 1 root serverless.yml
in a child example.module.yml i want to use the serverless.com variable resolution. 
See example


```yaml
functions:
  some-function:
    handler: index.doSomething
    environment:
      name: ${self:custom.test} #this does not get resolved
    events:
      - schedule: rate(1 hour)

```

But this doesnt work

As you can see in AWS lambda env:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/20506046/155596012-288d15c3-cbc7-473b-8e12-38968c341a9b.png">



Any solution on how to fix this ?
