### ISSUE TITLE
Resources are not merged together

### ISSUE THREAD

**Issue by LoZeno** [icarus-sullivan/serverless-plugin-modularize#2]
Despite what the Readme says, the plugin does not seem to actually merge the resources section of the modules:

have hello.module.yml define a resource section with a DynamoDB table
```
resources: 
  Resources:
      usersTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: usersTable
          AttributeDefinitions:
            - AttributeName: email
              AttributeType: S
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
```

have goodbye.module.yml define a resource section with another DynamoDB table:
```
resources: 
  Resources:
      carsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: carsTable
          AttributeDefinitions:
            - AttributeName: registration
              AttributeType: S
          KeySchema:
            - AttributeName: registration
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
```

then run the serverless deploy: the stack will contain only the resources of the last module loaded.
